// Single source of truth for the wizard questions, options, and presets.

export const steps = [
  {
    id: 'basics',
    title: 'Design brief',
    subtitle: 'What this site is and what it has to do.',
    fields: [
      {
        id: 'projectName',
        label: 'Project name',
        help: 'Used for the filename. Lowercase, no spaces.',
        type: 'text',
        required: true,
        placeholder: 'acme-co',
        transform: 'slug',
      },
      {
        id: 'displayName',
        label: 'Display name',
        help: 'How the brand is written in copy.',
        type: 'text',
        required: true,
        placeholder: 'Acme Co.',
      },
      {
        id: 'description',
        label: 'What does it do?',
        help: 'One sentence.',
        type: 'textarea',
        required: true,
        rows: 2,
        placeholder: 'A specialist physiotherapy clinic in Kent.',
      },
      {
        id: 'siteType',
        label: 'Website type',
        type: 'radio',
        required: true,
        options: [
          { value: 'marketing', label: 'Marketing site', caption: 'Sells a product or service. Homepage, features, pricing, contact.' },
          { value: 'product', label: 'Product or SaaS', caption: 'A live product with a signed-in experience and a marketing front.' },
          { value: 'portfolio', label: 'Portfolio', caption: 'Shows a person or studio\'s work to win new clients.' },
          { value: 'ecommerce', label: 'Ecommerce', caption: 'Sells goods with a cart and checkout.' },
          { value: 'blog', label: 'Blog or publication', caption: 'Article-led. Discovery matters.' },
          { value: 'app', label: 'Web app', caption: 'Task-led software. People come to get things done.' },
          { value: 'dashboard', label: 'Dashboard', caption: 'Data-dense internal tool. Clarity over flourish.' },
          { value: 'docs', label: 'Documentation', caption: 'Reference material for developers or power users.' },
          { value: 'local', label: 'Local service business', caption: 'Clinic, trades, hospitality. Trust and booking-focused.' },
        ],
      },
    ],
  },

  {
    id: 'audience',
    title: 'Audience and objective',
    subtitle: 'Who visits, and what they came for.',
    fields: [
      {
        id: 'audience',
        label: 'Who\'s it for?',
        help: 'Add your own, or pick from the suggestions.',
        type: 'chips',
        max: 3,
        writeIn: true,
        writeInFirst: true,
        writeInPlaceholder: 'Your audience',
        options: [
          'Founders', 'Product leads', 'Hiring managers',
          'Developers', 'Designers', 'Executives',
          'Clinicians', 'Patients', 'Carers',
          'Shoppers', 'Students', 'Creators',
          'Internal teams', 'Small business owners', 'Enterprise buyers',
          'Journalists', 'Investors', 'General public',
        ],
      },
      {
        id: 'context',
        label: 'When do they visit?',
        help: 'Up to three.',
        type: 'chips',
        max: 3,
        writeIn: true,
        writeInFirst: true,
        writeInPlaceholder: 'Your context',
        options: [
          'Quick recommendation check', 'Researching before buying',
          'Focused work session', 'Shared screen in a meeting',
          'Mobile on the go', 'Desktop at office',
          'Late-night panic', 'Morning browse',
          'Returning power user', 'First-time visitor',
        ],
      },
      {
        id: 'objectives',
        label: 'What do they need to do?',
        help: 'The outcomes the site has to drive.',
        type: 'chips',
        writeIn: true,
        writeInFirst: true,
        writeInPlaceholder: 'Your objective',
        options: [
          'Verify credibility',
          'Compare against alternatives',
          'Understand the offer',
          'Buy now',
          'Get help fast',
          'Book a service',
          'Generate qualified leads',
          'Build brand awareness',
          'Recruit the right hires',
          'Support existing customers',
          'Get users to sign up',
          'Drive a newsletter subscription',
          'Rank in search for key terms',
        ],
      },
    ],
  },

  {
    id: 'personality',
    title: 'Brand personality',
    subtitle: 'Three words. Concrete, not marketing.',
    fields: [
      {
        id: 'personality',
        label: 'Three words that describe it',
        help: '"Modern" and "elegant" don\'t mean anything. Be specific.',
        type: 'chips',
        max: 3,
        min: 1,
        required: true,
        writeIn: true,
        writeInFirst: true,
        writeInPlaceholder: 'Your word',
        options: [
          'warm', 'mechanical', 'opinionated', 'calm', 'clinical',
          'fast', 'dense', 'unimpressed', 'handmade', 'weird',
          'precise', 'irreverent', 'editorial', 'confident', 'approachable',
          'serious', 'playful', 'restrained', 'bold', 'quiet',
          'loud', 'refined', 'raw', 'considered', 'generous',
          'sharp', 'soft', 'direct', 'contemplative', 'optimistic',
          'technical', 'crafted', 'honest',
        ],
      },
      {
        id: 'emotion',
        label: 'How should it feel?',
        help: 'Pick one.',
        type: 'chips',
        max: 1,
        min: 1,
        required: true,
        writeIn: true,
        writeInFirst: true,
        writeInPlaceholder: 'Your emotion',
        options: [
          'Confidence', 'Calm', 'Delight', 'Urgency',
          'Trust', 'Curiosity', 'Focus', 'Warmth',
        ],
      },
    ],
  },

  {
    id: 'aesthetic',
    title: 'Aesthetic direction',
    subtitle: 'What it should feel like.',
    fields: [
      {
        id: 'visualTone',
        label: 'Visual tone',
        help: 'Pick the one that fits.',
        type: 'gallery',
        required: true,
        options: [
          { value: 'brutally-minimal', label: 'Brutally minimal', blurb: 'Almost nothing, then one sharp move.',
            palette: ['#f7f6f3', '#e6e3dc', '#1a1a1a', '#8a8680', '#c3392e'] },
          { value: 'warm-editorial', label: 'Warm editorial', blurb: 'Magazine sensibility, approachable.',
            palette: ['#edecea', '#c7a17a', '#1c4831', '#b03a2e', '#c49a02'] },
          { value: 'maximalist', label: 'Maximalist', blurb: 'Dense, layered, loud on purpose.',
            palette: ['#f5e9d7', '#ff5a1f', '#6a2cd6', '#19b67a', '#1a1a1a'] },
          { value: 'retro-futurist', label: 'Retro-futurist', blurb: '1970s mainframe meets tomorrow.',
            palette: ['#0c1a2b', '#1f3a5f', '#e7c85c', '#d94e4e', '#a3b8c9'] },
          { value: 'organic', label: 'Organic', blurb: 'Natural forms, soft edges, earthy.',
            palette: ['#ece5d4', '#a8b893', '#4b5a3e', '#c28e4a', '#2e3324'] },
          { value: 'luxury', label: 'Luxury', blurb: 'Refined, expensive, quiet.',
            palette: ['#181613', '#e9dfd1', '#b69660', '#3a332d', '#7a6a52'] },
          { value: 'playful', label: 'Playful', blurb: 'Toy-like, generous, lightly absurd.',
            palette: ['#fff4c2', '#ff6b9d', '#4cc2ff', '#3a3a3a', '#76e085'] },
          { value: 'brutalist', label: 'Brutalist', blurb: 'Raw, structural, unvarnished.',
            palette: ['#d9d7d2', '#0a0a0a', '#e64b1e', '#f2f0eb', '#9c9892'] },
          { value: 'art-deco', label: 'Art deco', blurb: 'Geometric, ornamented, stately.',
            palette: ['#1a1a1a', '#c9a243', '#e9e1c9', '#6b1f2a', '#2e4a3a'] },
          { value: 'soft-pastel', label: 'Soft pastel', blurb: 'Gentle, muted, reassuring.',
            palette: ['#fbeef0', '#f5d0d9', '#cbe2d9', '#d4c9e8', '#4a4156'] },
          { value: 'industrial', label: 'Industrial', blurb: 'Utilitarian, precise, no fluff.',
            palette: ['#b8b3ab', '#3f4448', '#1a1d20', '#d9d4cb', '#c94a1f'] },
          { value: 'technical', label: 'Technical document', blurb: 'Spec-sheet precision.',
            palette: ['#ffffff', '#e5e5e5', '#1a1a1a', '#0057b7', '#d1d1d1'] },
        ],
      },
      {
        id: 'theme',
        label: 'Light or dark',
        help: 'Think about when and where people use it.',
        type: 'radio',
        required: true,
        options: [
          { value: 'light', label: 'Light' },
          { value: 'dark', label: 'Dark' },
          { value: 'both', label: 'Both, user toggleable' },
          { value: 'auto', label: 'Auto, follow system' },
        ],
      },
      {
        id: 'references',
        label: 'References',
        help: 'Paste URLs or pick from the list. Click once for inspiration, twice to avoid.',
        type: 'references',
        groups: [
          { name: 'AI and ML', items: ['Claude', 'Cohere', 'ElevenLabs', 'Minimax', 'Mistral AI', 'Ollama', 'OpenCode AI', 'Replicate', 'RunwayML', 'Together AI', 'VoltAgent', 'xAI'] },
          { name: 'Dev tools', items: ['Cursor', 'Expo', 'Lovable', 'Raycast', 'Superhuman', 'Vercel', 'Warp'] },
          { name: 'Developer platforms', items: ['ClickHouse', 'Composio', 'HashiCorp', 'MongoDB', 'PostHog', 'Sanity', 'Sentry', 'Supabase'] },
          { name: 'SaaS', items: ['Cal.com', 'Intercom', 'Linear', 'Mintlify', 'Notion', 'Resend', 'Zapier'] },
          { name: 'Design and creative', items: ['Airtable', 'Clay', 'Figma', 'Framer', 'Miro', 'Webflow'] },
          { name: 'Fintech', items: ['Binance', 'Coinbase', 'Kraken', 'Mastercard', 'Revolut', 'Stripe', 'Wise'] },
          { name: 'Consumer and brand', items: ['Airbnb', 'Apple', 'IBM', 'Meta', 'Nike', 'NVIDIA', 'Pinterest', 'PlayStation', 'Shopify', 'SpaceX', 'Spotify', 'The Verge', 'Uber', 'Vodafone', 'WIRED'] },
          { name: 'Automotive', items: ['BMW', 'Bugatti', 'Ferrari', 'Lamborghini', 'Renault', 'Tesla'] },
        ],
      },
      {
        id: 'antiPatterns',
        label: 'Avoid',
        help: 'Patterns the site should not use. One per line.',
        type: 'textarea',
        rows: 4,
        placeholder: 'Glassmorphism everywhere\nCyan-on-dark gradients\nTemplate-looking card grids',
      },
    ],
  },

  {
    id: 'seeds',
    title: 'Colour and type',
    subtitle: 'Optional. Skip if you want me to pick.',
    fields: [
      {
        id: 'brandHue',
        label: 'Brand colour',
        help: 'A starting hue. Not a final palette.',
        type: 'color',
      },
      {
        id: 'neutralTemp',
        label: 'Grey tint',
        help: 'How the greys should feel.',
        type: 'radioVisual',
        options: [
          { value: 'warm', label: 'Warm', caption: 'Cream, stone, sand.', swatches: ['#f4efe7', '#e3dacb', '#c7b89d', '#8c7e66', '#3e3a33'] },
          { value: 'cool', label: 'Cool', caption: 'Slate, steel, fog.', swatches: ['#eef1f3', '#d4dbe0', '#a7b3bd', '#5b6a77', '#2a333a'] },
          { value: 'neutral', label: 'Neutral', caption: 'True greys.', swatches: ['#f2f2f2', '#dcdcdc', '#b0b0b0', '#6a6a6a', '#2b2b2b'] },
          { value: 'tinted', label: 'Tinted', caption: 'Pulled toward the brand hue.', swatches: ['#eef0ea', '#d8ddcf', '#a9b0a0', '#5b6356', '#252a24'] },
        ],
      },
      {
        id: 'typePair',
        label: 'Type direction',
        help: 'Specific fonts picked at build time.',
        type: 'typePair',
        options: [
          { value: 'editorial-serif', label: 'Editorial serif + clean sans',
            displayFont: '"Didot", "Bodoni MT", serif',
            bodyFont: '"Helvetica Neue", Helvetica, Arial, sans-serif',
            displayWeight: 400 },
          { value: 'geometric-sans', label: 'Geometric sans + humanist sans',
            displayFont: '"Futura", "Century Gothic", sans-serif',
            bodyFont: '"Lucida Grande", "Lucida Sans", sans-serif',
            displayWeight: 500 },
          { value: 'grotesk-serif', label: 'Heavy grotesk + serif body',
            displayFont: '"Arial Black", "Helvetica Neue", sans-serif',
            bodyFont: 'Georgia, "Times New Roman", serif',
            displayWeight: 900 },
          { value: 'mono-display', label: 'Mono display + sans body',
            displayFont: 'Menlo, "Courier New", monospace',
            bodyFont: '"Helvetica Neue", Helvetica, sans-serif',
            displayWeight: 500 },
          { value: 'all-serif', label: 'Serif display + serif body',
            displayFont: '"Hoefler Text", "Baskerville", serif',
            bodyFont: 'Georgia, "Times New Roman", serif',
            displayWeight: 500 },
          { value: 'all-sans', label: 'One sans, varied weights',
            displayFont: '"Helvetica Neue", Helvetica, Arial, sans-serif',
            bodyFont: '"Helvetica Neue", Helvetica, Arial, sans-serif',
            displayWeight: 300 },
          { value: 'handmade', label: 'Handmade display + serif body',
            displayFont: '"Brush Script MT", "Snell Roundhand", cursive',
            bodyFont: 'Georgia, "Times New Roman", serif',
            displayWeight: 400 },
        ],
      },
    ],
  },

  {
    id: 'constraints',
    title: 'Constraints',
    subtitle: 'The non-negotiables.',
    fields: [
      {
        id: 'accessibility',
        label: 'Accessibility',
        help: 'AA is the baseline for nearly every project.',
        type: 'radio',
        required: true,
        default: 'AA',
        options: [
          { value: 'AA', label: 'WCAG 2.2 AA', caption: 'Sufficient contrast, keyboard support, visible focus, alt text on non-decorative imagery.' },
          { value: 'AAA', label: 'WCAG 2.2 AAA', caption: 'Stricter contrast and clarity. Often incompatible with rich imagery.' },
          { value: 'custom', label: 'Custom', caption: 'Bespoke requirements. Describe them in the notes.' },
        ],
      },
      {
        id: 'reducedMotion',
        label: 'Motion',
        help: 'Respect system preferences.',
        type: 'checkboxes',
        merge: true,
        options: ['Respect prefers-reduced-motion', 'Provide a motion toggle in the UI'],
      },
      {
        id: 'accessibilityNotes',
        label: 'Notes',
        help: 'Specifics: audience needs, required AT support, regional rules.',
        type: 'textarea',
        merge: true,
        rows: 2,
        placeholder: 'Older audience. Many use screen magnifiers. 18px body minimum.',
      },
      {
        id: 'performance',
        label: 'Performance',
        type: 'radio',
        options: [
          { value: 'speed', label: 'Speed first', caption: 'Static output, minimal JS, aggressive optimisation.' },
          { value: 'balanced', label: 'Balanced', caption: 'JS where it earns its weight.' },
          { value: 'rich', label: 'Rich and interactive', caption: 'Animation, canvas, heavy interactivity fine where justified.' },
        ],
      },
      {
        id: 'stack',
        label: 'Stack',
        help: 'What\'s in play, or what you\'ll use.',
        type: 'chips',
        writeIn: true,
        writeInFirst: true,
        writeInPlaceholder: 'Your tool',
        options: [
          { value: 'Astro', icon: 'astro' },
          { value: 'Next.js', icon: 'next' },
          { value: 'Remix', icon: 'remix' },
          { value: 'SvelteKit', icon: 'svelte' },
          { value: 'WordPress', icon: 'wp' },
          { value: 'Framer', icon: 'framer' },
          { value: 'Plain HTML/CSS/JS', icon: 'html' },
          { value: 'React island', icon: 'react' },
          { value: 'GSAP', icon: 'gsap' },
          { value: 'Tailwind', icon: 'tw' },
          { value: 'Plain CSS', icon: 'css' },
          { value: 'Cloudflare Pages', icon: 'cf' },
          { value: 'Vercel', icon: 'vercel' },
        ],
      },
      {
        id: 'language',
        label: 'Spelling',
        type: 'radio',
        default: 'en-GB',
        options: [
          { value: 'en-GB', label: 'British English', caption: 'colour, realise, behaviour, centre, organise.' },
          { value: 'en-US', label: 'American English', caption: 'color, realize, behavior, center, organize.' },
          { value: 'other', label: 'Other', caption: 'Fill in below.' },
        ],
      },
      {
        id: 'languageOther',
        label: 'Which language?',
        help: 'Leave blank unless you picked Other above.',
        type: 'text',
        merge: true,
        placeholder: 'French, Dutch, Japanese',
      },
      {
        id: 'notes',
        label: 'Anything else',
        help: 'Constraints, context, warnings.',
        type: 'textarea',
        rows: 3,
        placeholder: 'Legal has to sign off any claims. Launch tied to Q3.',
      },
    ],
  },
];

// Site-type-driven defaults. Used only if state is empty on first visit.
export const presets = {
  marketing: { audience: ['Founders', 'Product leads'], context: ['Researching before buying'], emotion: ['Confidence'], visualTone: 'warm-editorial', theme: 'light', performance: 'speed' },
  product: { audience: ['Product leads', 'Developers'], context: ['Focused work session'], emotion: ['Focus'], visualTone: 'technical', theme: 'both', performance: 'balanced' },
  portfolio: { audience: ['Hiring managers', 'Founders'], context: ['Quick recommendation check'], emotion: ['Confidence'], visualTone: 'warm-editorial', theme: 'light', performance: 'speed' },
  ecommerce: { audience: ['Shoppers'], context: ['Mobile on the go'], emotion: ['Trust'], visualTone: 'luxury', theme: 'light', performance: 'speed' },
  blog: { audience: ['General public'], context: ['Morning browse'], emotion: ['Curiosity'], visualTone: 'warm-editorial', theme: 'light', performance: 'speed' },
  app: { audience: ['Internal teams'], context: ['Focused work session'], emotion: ['Focus'], visualTone: 'industrial', theme: 'both', performance: 'rich' },
  dashboard: { audience: ['Internal teams', 'Executives'], context: ['Focused work session'], emotion: ['Focus'], visualTone: 'technical', theme: 'dark', performance: 'balanced' },
  docs: { audience: ['Developers'], context: ['Focused work session'], emotion: ['Focus'], visualTone: 'technical', theme: 'both', performance: 'speed' },
  local: { audience: ['General public'], context: ['Mobile on the go'], emotion: ['Trust'], visualTone: 'warm-editorial', theme: 'light', performance: 'speed' },
};
